### ISSUE TITLE
bug report in midiXparser.cpp

### ISSUE THREAD

**Issue by mirinz** [TheKikGen/midiXparser#1]
line 378: m_midiMsg[3-m_nextMidiMsglen] = readByte;
there is wrong index for 2 bytes MIDI messages (Cx or Dx). m_nextMidiMsglen equals 1 so the second byte of the MIDI message is written to the third byte of m_midiMsg

**Comment by TheKikGen** [comment]
Thanks.  Issue solved.  Closed with the last commit.  
Concerned only Program Change and Aftertouch channel messages hopefully.
Please confirm the correct behaviour now.
