### ISSUE TITLE
'class midiXparser' has no member named 'setRealTimeMsgFilter' in the ino example 

### ISSUE THREAD

**Issue by VordV** [TheKikGen/midiXparser#2]
Hi, I really would love a MIDI parser that's fast, lightweight, and easy to use for a simple sysex function.  I tried yours out, but the included example does not compile, it just throws this error.

```

C:\Program Files (x86)\Arduino\libraries\midiXparser-master\midiXParser-example\midiXparser-example.ino: In function 'void setup()':

midiXparser-example:42:15: error: 'class midiXparser' has no member named 'setRealTimeMsgFilter'

   midiParser2.setRealTimeMsgFilter(midiXparser::realTimeMsgTypeMsk  );

               ^

C:\Program Files (x86)\Arduino\libraries\midiXparser-master\midiXParser-example\midiXparser-example.ino: In function 'void loop()':

midiXparser-example:55:56: error: invalid types '<unresolved overloaded function type>[int]' for array subscript

           uint8_t midiStatus = midiParser1.getMidiMsg[0] & 0xF0;

                                                        ^

exit status 1
'class midiXparser' has no member named 'setRealTimeMsgFilter'
```

**Comment by TheKikGen** [comment]
Hello.

Use instead midiParser2.setMidiMsgFilter(midiXparser::realTimeMsgTypeMsk  );
This old example wasn't updated.

You can also check other examples in the "midiXParser-tests" directory github repo.

Issue closed.
This doesn't concern the midiXParser class itself, only the example. Example adjusted and committed.

**Comment by TheKikGen** [comment]
# Issue closed #   Example adjusted and committed #.
